proc __tcl3dGetStateList {} {
return {
{ glGetFloatv GL_CURRENT_COLOR 4 1,1,1,1 }
{ glGetFloatv GL_CURRENT_SECONDARY_COLOR 4 0,0,0,1 }
{ glGetFloatv GL_CURRENT_INDEX 1 1 }
{ glGetFloatv GL_CURRENT_TEXTURE_COORDS 4 0,0,0,1 }
{ glGetFloatv GL_CURRENT_NORMAL 3 0,0,1 }
{ glGetFloatv GL_CURRENT_FOG_COORD 1 0 }
{ glGetFloatv GL_CURRENT_RASTER_POSITION 4 0,0,0,1 }
{ glGetFloatv GL_CURRENT_RASTER_DISTANCE 1 0 }
{ glGetFloatv GL_CURRENT_RASTER_COLOR 4 1,1,1,1 }
{ glGetIntegerv GL_CURRENT_RASTER_INDEX 1 1 }
{ glGetFloatv GL_CURRENT_RASTER_TEXTURE_COORDS 4 0,0,0,1 }
{ glGetBooleanv GL_CURRENT_RASTER_POSITION_VALID 1 True }
{ glGetBooleanv GL_EDGE_FLAG 1 True }
{ glGetIntegerv GL_CLIENT_ACTIVE_TEXTURE 1 TEXTURE0 }
{ glIsEnabled GL_VERTEX_ARRAY 1 False }
{ glGetIntegerv GL_VERTEX_ARRAY_SIZE 1 4 }
{ glGetIntegerv GL_VERTEX_ARRAY_TYPE 1 FLOAT }
{ glGetIntegerv GL_VERTEX_ARRAY_STRIDE 1 0 }
{ glGetPointerv GL_VERTEX_ARRAY_POINTER 1 0 }
{ glIsEnabled GL_NORMAL_ARRAY 1 False }
{ glGetIntegerv GL_NORMAL_ARRAY_TYPE 1 FLOAT }
{ glGetIntegerv GL_NORMAL_ARRAY_STRIDE 1 0 }
{ glGetPointerv GL_NORMAL_ARRAY_POINTER 1 0 }
{ glIsEnabled GL_FOG_COORD_ARRAY 1 False }
{ glGetIntegerv GL_FOG_COORD_ARRAY_TYPE 1 FLOAT }
{ glGetIntegerv GL_FOG_COORD_ARRAY_STRIDE 1 0 }
{ glGetPointerv GL_FOG_COORD_ARRAY_POINTER 1 0 }
{ glIsEnabled GL_COLOR_ARRAY 1 False }
{ glGetIntegerv GL_COLOR_ARRAY_SIZE 1 4 }
{ glGetIntegerv GL_COLOR_ARRAY_TYPE 1 FLOAT }
{ glGetIntegerv GL_COLOR_ARRAY_STRIDE 1 0 }
{ glGetPointerv GL_COLOR_ARRAY_POINTER 1 0 }
{ glIsEnabled GL_SECONDARY_COLOR_ARRAY 1 False }
{ glGetIntegerv GL_SECONDARY_COLOR_ARRAY_SIZE 1 3 }
{ glGetIntegerv GL_SECONDARY_COLOR_ARRAY_TYPE 1 FLOAT }
{ glGetIntegerv GL_SECONDARY_COLOR_ARRAY_STRIDE 1 0 }
{ glGetPointerv GL_SECONDARY_COLOR_ARRAY_POINTER 1 0 }
{ glIsEnabled GL_INDEX_ARRAY 1 False }
{ glGetIntegerv GL_INDEX_ARRAY_TYPE 1 FLOAT }
{ glGetIntegerv GL_INDEX_ARRAY_STRIDE 1 0 }
{ glGetPointerv GL_INDEX_ARRAY_POINTER 1 0 }
{ glIsEnabled GL_TEXTURE_COORD_ARRAY 1 False }
{ glGetIntegerv GL_TEXTURE_COORD_ARRAY_SIZE 1 4 }
{ glGetIntegerv GL_TEXTURE_COORD_ARRAY_TYPE 1 FLOAT }
{ glGetIntegerv GL_TEXTURE_COORD_ARRAY_STRIDE 1 0 }
{ glGetPointerv GL_TEXTURE_COORD_ARRAY_POINTER 1 0 }
{ glGetVertexAttribiv GL_VERTEX_ATTRIB_ARRAY_ENABLED 1 False }
{ glGetVertexAttribiv GL_VERTEX_ATTRIB_ARRAY_SIZE 1 4 }
{ glGetVertexAttribiv GL_VERTEX_ATTRIB_ARRAY_STRIDE 1 0 }
{ glGetVertexAttribiv GL_VERTEX_ATTRIB_ARRAY_TYPE 1 FLOAT }
{ glGetVertexAttribiv GL_VERTEX_ATTRIB_ARRAY_NORMALIZED 1 False }
{ glGetVertexAttribPointerv GL_VERTEX_ATTRIB_ARRAY_POINTER 1 NULL }
{ glIsEnabled GL_EDGE_FLAG_ARRAY 1 False }
{ glGetIntegerv GL_EDGE_FLAG_ARRAY_STRIDE 1 0 }
{ glGetPointerv GL_EDGE_FLAG_ARRAY_POINTER 1 0 }
{ glGetIntegerv GL_ARRAY_BUFFER_BINDING 1 0 }
{ glGetIntegerv GL_VERTEX_ARRAY_BUFFER_BINDING 1 0 }
{ glGetIntegerv GL_NORMAL_ARRAY_BUFFER_BINDING 1 0 }
{ glGetIntegerv GL_COLOR_ARRAY_BUFFER_BINDING 1 0 }
{ glGetIntegerv GL_INDEX_ARRAY_BUFFER_BINDING 1 0 }
{ glGetIntegerv GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING 1 0 }
{ glGetIntegerv GL_EDGE_FLAG_ARRAY_BUFFER_BINDING 1 0 }
{ glGetIntegerv GL_SECONDARY_COLOR_ARRAY_BUFFER_BINDING 1 0 }
{ glGetIntegerv GL_FOG_COORD_ARRAY_BUFFER_BINDING 1 0 }
{ glGetIntegerv GL_ELEMENT_ARRAY_BUFFER_BINDING 1 0 }
{ glGetBufferSubData - 1 - }
{ glGetBufferParameteriv GL_BUFFER_SIZE 1 0 }
{ glGetBufferParameteriv GL_BUFFER_USAGE 1 STATIC_DRAW }
{ glGetBufferParameteriv GL_BUFFER_ACCESS 1 READ_WRITE }
{ glGetBufferParameteriv GL_BUFFER_MAPPED 1 FALSE }
{ glGetBufferPointerv GL_BUFFER_MAP_POINTER 1 NULL }
{ glGetFloatv GL_COLOR_MATRIX 16 Identity }
{ glGetFloatv GL_TRANSPOSE_COLOR_MATRIX 16 Identity }
{ glGetFloatv GL_MODELVIEW_MATRIX 16 Identity }
{ glGetFloatv GL_TRANSPOSE_MODELVIEW_MATRIX 16 Identity }
{ glGetFloatv GL_PROJECTION_MATRIX 16 Identity }
{ glGetFloatv GL_TRANSPOSE_PROJECTION_MATRIX 16 Identity }
{ glGetFloatv GL_TEXTURE_MATRIX 16 Identity }
{ glGetFloatv GL_TRANSPOSE_TEXTURE_MATRIX 16 Identity }
{ glGetIntegerv GL_VIEWPORT 1 {see 2.11.1} }
{ glGetFloatv GL_DEPTH_RANGE 2 0,1 }
{ glGetIntegerv GL_COLOR_MATRIX_STACK_DEPTH 1 1 }
{ glGetIntegerv GL_MODELVIEW_STACK_DEPTH 1 1 }
{ glGetIntegerv GL_PROJECTION_STACK_DEPTH 1 1 }
{ glGetIntegerv GL_TEXTURE_STACK_DEPTH 1 1 }
{ glGetIntegerv GL_MATRIX_MODE 1 MODELVIEW }
{ glIsEnabled GL_NORMALIZE 1 False }
{ glIsEnabled GL_RESCALE_NORMAL 1 False }
{ glGetClipPlane GL_CLIP_PLANE0 4 0,0,0,0 }
{ glGetClipPlane GL_CLIP_PLANE1 4 0,0,0,0 }
{ glGetClipPlane GL_CLIP_PLANE2 4 0,0,0,0 }
{ glGetClipPlane GL_CLIP_PLANE3 4 0,0,0,0 }
{ glGetClipPlane GL_CLIP_PLANE4 4 0,0,0,0 }
{ glGetClipPlane GL_CLIP_PLANE5 4 0,0,0,0 }
{ glIsEnabled GL_CLIP_PLANE0 1 False }
{ glIsEnabled GL_CLIP_PLANE1 1 False }
{ glIsEnabled GL_CLIP_PLANE2 1 False }
{ glIsEnabled GL_CLIP_PLANE3 1 False }
{ glIsEnabled GL_CLIP_PLANE4 1 False }
{ glIsEnabled GL_CLIP_PLANE5 1 False }
{ glGetFloatv GL_FOG_COLOR 4 0,0,0,0 }
{ glGetFloatv GL_FOG_INDEX 1 0 }
{ glGetFloatv GL_FOG_DENSITY 1 1.0 }
{ glGetFloatv GL_FOG_START 1 0.0 }
{ glGetFloatv GL_FOG_END 1 1.0 }
{ glGetIntegerv GL_FOG_MODE 1 EXP }
{ glIsEnabled GL_FOG 1 False }
{ glGetIntegerv GL_FOG_COORD_SOURCE 1 FRAGMENT_DEPTH }
{ glIsEnabled GL_COLOR_SUM 1 False }
{ glGetIntegerv GL_SHADE_MODEL 1 SMOOTH }
{ glIsEnabled GL_LIGHTING 1 False }
{ glIsEnabled GL_COLOR_MATERIAL 1 False }
{ glGetIntegerv GL_COLOR_MATERIAL_PARAMETER 1 AMBIENT_AND_DIFFUSE }
{ glGetIntegerv GL_COLOR_MATERIAL_FACE 1 FRONT_AND_BACK }
{ glGetMaterialfv GL_AMBIENT 4 0.2,0.2,0.2,1.0 }
{ glGetMaterialfv GL_DIFFUSE 4 0.8,0.8,0.8,1.0 }
{ glGetMaterialfv GL_SPECULAR 4 0.0,0.0,0.0,1.0 }
{ glGetMaterialfv GL_EMISSION 4 0.0,0.0,0.0,1.0 }
{ glGetMaterialfv GL_SHININESS 1 0.0 }
{ glGetFloatv GL_LIGHT_MODEL_AMBIENT 4 0.2,0.2,0.2,1.0 }
{ glGetBooleanv GL_LIGHT_MODEL_LOCAL_VIEWER 1 False }
{ glGetBooleanv GL_LIGHT_MODEL_TWO_SIDE 1 False }
{ glGetIntegerv GL_LIGHT_MODEL_COLOR_CONTROL 1 SINGLE_COLOR }
{ glGetLightfv GL_AMBIENT 4 0.0,0.0,0.0,1.0 }
{ glGetLightfv GL_DIFFUSE 1 {see table 2.10} }
{ glGetLightfv GL_SPECULAR 1 {see table 2.10} }
{ glGetLightfv GL_POSITION 4 0.0,0.0,1.0,0.0 }
{ glGetLightfv GL_CONSTANT_ATTENUATION 1 1.0 }
{ glGetLightfv GL_LINEAR_ATTENUATION 1 0.0 }
{ glGetLightfv GL_QUADRATIC_ATTENUATION 1 0.0 }
{ glGetLightfv GL_SPOT_DIRECTION 3 0.0,0.0,-1.0 }
{ glGetLightfv GL_SPOT_EXPONENT 1 0.0 }
{ glGetLightfv GL_SPOT_CUTOFF 1 180.0 }
{ glIsEnabled GL_LIGHT0 1 False }
{ glIsEnabled GL_LIGHT1 1 False }
{ glIsEnabled GL_LIGHT2 1 False }
{ glIsEnabled GL_LIGHT3 1 False }
{ glIsEnabled GL_LIGHT4 1 False }
{ glIsEnabled GL_LIGHT5 1 False }
{ glIsEnabled GL_LIGHT6 1 False }
{ glIsEnabled GL_LIGHT7 1 False }
{ glGetMaterialfv GL_COLOR_INDEXES 3 0,1,1 }
{ glGetFloatv GL_POINT_SIZE 1 1.0 }
{ glIsEnabled GL_POINT_SMOOTH 1 False }
{ glIsEnabled GL_POINT_SPRITE 1 False }
{ glGetFloatv GL_POINT_SIZE_MIN 1 0.0 }
{ glGetFloatv GL_POINT_SIZE_MAX 1 1 }
{ glGetFloatv GL_POINT_FADE_THRESHOLD_SIZE 1 1.0 }
{ glGetFloatv GL_POINT_DISTANCE_ATTENUATION 3 1,0,0 }
{ glGetIntegerv GL_POINT_SPRITE_COORD_ORIGIN 1 UPPER_LEFT }
{ glGetFloatv GL_LINE_WIDTH 1 1.0 }
{ glIsEnabled GL_LINE_SMOOTH 1 False }
{ glGetIntegerv GL_LINE_STIPPLE_PATTERN 1 1's }
{ glGetIntegerv GL_LINE_STIPPLE_REPEAT 1 1 }
{ glIsEnabled GL_LINE_STIPPLE 1 False }
{ glIsEnabled GL_CULL_FACE 1 False }
{ glGetIntegerv GL_CULL_FACE_MODE 1 BACK }
{ glGetIntegerv GL_FRONT_FACE 1 CCW }
{ glIsEnabled GL_POLYGON_SMOOTH 1 False }
{ glGetIntegerv GL_POLYGON_MODE 1 FILL }
{ glGetFloatv GL_POLYGON_OFFSET_FACTOR 1 0 }
{ glGetFloatv GL_POLYGON_OFFSET_UNITS 1 0 }
{ glIsEnabled GL_POLYGON_OFFSET_POINT 1 False }
{ glIsEnabled GL_POLYGON_OFFSET_LINE 1 False }
{ glIsEnabled GL_POLYGON_OFFSET_FILL 1 False }
{ glGetPolygonStipple - 1 1's }
{ glIsEnabled GL_POLYGON_STIPPLE 1 False }
{ glIsEnabled GL_MULTISAMPLE 1 True }
{ glIsEnabled GL_SAMPLE_ALPHA_TO_COVERAGE 1 False }
{ glIsEnabled GL_SAMPLE_ALPHA_TO_ONE 1 False }
{ glIsEnabled GL_SAMPLE_COVERAGE 1 False }
{ glGetFloatv GL_SAMPLE_COVERAGE_VALUE 1 1 }
{ glGetBooleanv GL_SAMPLE_COVERAGE_INVERT 1 False }
{ glIsEnabled GL_TEXTURE_1D 1 False }
{ glIsEnabled GL_TEXTURE_2D 1 False }
{ glIsEnabled GL_TEXTURE_3D 1 False }
{ glIsEnabled GL_TEXTURE_CUBE_MAP 1 False }
{ glGetIntegerv GL_TEXTURE_BINDING_1D 1 0 }
{ glGetIntegerv GL_TEXTURE_BINDING_2D 1 0 }
{ glGetIntegerv GL_TEXTURE_BINDING_3D 1 0 }
{ glGetIntegerv GL_TEXTURE_BINDING_CUBE_MAP 1 0 }
{ glGetTexImage GL_TEXTURE_1D 1 {see 3.8} }
{ glGetTexImage GL_TEXTURE_2D 1 {see 3.8} }
{ glGetTexImage GL_TEXTURE_3D 1 {see 3.8} }
{ glGetTexImage GL_TEXTURE_CUBE_MAP_POSITIVE_X 1 {see 3.8.1} }
{ glGetTexImage GL_TEXTURE_CUBE_MAP_NEGATIVE_X 1 {see 3.8.1} }
{ glGetTexImage GL_TEXTURE_CUBE_MAP_POSITIVE_Y 1 {see 3.8.1} }
{ glGetTexImage GL_TEXTURE_CUBE_MAP_NEGATIVE_Y 1 {see 3.8.1} }
{ glGetTexImage GL_TEXTURE_CUBE_MAP_POSITIVE_Z 1 {see 3.8.1} }
{ glGetTexImage GL_TEXTURE_CUBE_MAP_NEGATIVE_Z 1 {see 3.8.1} }
{ glGetTexParameterfv GL_TEXTURE_BORDER_COLOR 4 0,0,0,0 }
{ glGetTexParameteriv GL_TEXTURE_MIN_FILTER 1 {see 3.8} }
{ glGetTexParameteriv GL_TEXTURE_MAG_FILTER 1 {see 3.8} }
{ glGetTexParameteriv GL_TEXTURE_WRAP_S 1 REPEAT }
{ glGetTexParameteriv GL_TEXTURE_WRAP_T 1 REPEAT }
{ glGetTexParameteriv GL_TEXTURE_WRAP_R 1 REPEAT }
{ glGetTexParameterfv GL_TEXTURE_PRIORITY 1 1 }
{ glGetTexParameteriv GL_TEXTURE_RESIDENT 1 {see 3.8.12} }
{ glGetTexParameterfv GL_TEXTURE_MIN_LOD 1 -1000 }
{ glGetTexParameterfv GL_TEXTURE_MAX_LOD 1 1000 }
{ glGetTexParameteriv GL_TEXTURE_BASE_LEVEL 1 0 }
{ glGetTexParameteriv GL_TEXTURE_MAX_LEVEL 1 1000 }
{ glGetTexParameterfv GL_TEXTURE_LOD_BIAS 1 0.0 }
{ glGetTexParameteriv GL_DEPTH_TEXTURE_MODE 1 LUMINANCE }
{ glGetTexParameteriv GL_TEXTURE_COMPARE_MODE 1 NONE }
{ glGetTexParameteriv GL_TEXTURE_COMPARE_FUNC 1 LEQUAL }
{ glGetTexParameteriv GL_GENERATE_MIPMAP 1 FALSE }
{ glGetTexLevelParameteriv GL_TEXTURE_WIDTH 1 0 }
{ glGetTexLevelParameteriv GL_TEXTURE_HEIGHT 1 0 }
{ glGetTexLevelParameteriv GL_TEXTURE_DEPTH 1 {0 3D} }
{ glGetTexLevelParameteriv GL_TEXTURE_BORDER 1 0 }
{ glGetTexLevelParameteriv GL_TEXTURE_INTERNAL_FORMAT 1 1 }
{ glGetTexLevelParameteriv GL_TEXTURE_RED_SIZE 1 0 }
{ glGetTexLevelParameteriv GL_TEXTURE_GREEN_SIZE 1 0 }
{ glGetTexLevelParameteriv GL_TEXTURE_BLUE_SIZE 1 0 }
{ glGetTexLevelParameteriv GL_TEXTURE_ALPHA_SIZE 1 0 }
{ glGetTexLevelParameteriv GL_TEXTURE_LUMINANCE_SIZE 1 0 }
{ glGetTexLevelParameteriv GL_TEXTURE_INTENSITY_SIZE 1 0 }
{ glGetTexLevelParameteriv GL_TEXTURE_DEPTH_SIZE 1 0 }
{ glGetTexLevelParameteriv GL_TEXTURE_COMPRESSED 1 False }
{ glGetTexLevelParameteriv GL_TEXTURE_COMPRESSED_IMAGE_SIZE 1 0 }
{ glGetTexEnviv GL_COORD_REPLACE 1 False }
{ glGetIntegerv GL_ACTIVE_TEXTURE 1 TEXTURE0 }
{ glGetTexEnviv GL_TEXTURE_ENV_MODE 1 MODULATE }
{ glGetTexEnvfv GL_TEXTURE_ENV_COLOR 4 0,0,0,0 }
{ glGetTexEnvfv GL_TEXTURE_LOD_BIAS 1 0.0 }
{ glIsEnabled GL_TEXTURE_GEN_S 1 False }
{ glIsEnabled GL_TEXTURE_GEN_T 1 False }
{ glIsEnabled GL_TEXTURE_GEN_R 1 False }
{ glIsEnabled GL_TEXTURE_GEN_Q 1 False }
{ glGetTexGenfv GL_EYE_PLANE 1 {see 2.11.4} }
{ glGetTexGenfv GL_OBJECT_PLANE 1 {see 2.11.4} }
{ glGetTexGeniv GL_TEXTURE_GEN_MODE 1 EYE_LINEAR }
{ glGetTexEnviv GL_COMBINE_RGB 1 MODULATE }
{ glGetTexEnviv GL_COMBINE_ALPHA 1 MODULATE }
{ glGetTexEnviv GL_SRC0_RGB 1 TEXTURE }
{ glGetTexEnviv GL_SRC1_RGB 1 PREVIOUS }
{ glGetTexEnviv GL_SRC2_RGB 1 CONSTANT }
{ glGetTexEnviv GL_SRC0_ALPHA 1 TEXTURE }
{ glGetTexEnviv GL_SRC1_ALPHA 1 PREVIOUS }
{ glGetTexEnviv GL_SRC2_ALPHA 1 CONSTANT }
{ glGetTexEnviv GL_OPERAND0_RGB 1 SRC_COLOR }
{ glGetTexEnviv GL_OPERAND1_RGB 1 SRC_COLOR }
{ glGetTexEnviv GL_OPERAND2_RGB 1 {SRC ALPHA} }
{ glGetTexEnviv GL_OPERAND0_ALPHA 1 {SRC ALPHA} }
{ glGetTexEnviv GL_OPERAND1_ALPHA 1 {SRC ALPHA} }
{ glGetTexEnviv GL_OPERAND2_ALPHA 1 SRC_ALPHA }
{ glGetTexEnvfv GL_RGB_SCALE 1 1.0 }
{ glGetTexEnvfv GL_ALPHA_SCALE 1 1.0 }
{ glIsEnabled GL_SCISSOR_TEST 1 False }
{ glGetIntegerv GL_SCISSOR_BOX 1 {see 4.1.2} }
{ glIsEnabled GL_ALPHA_TEST 1 False }
{ glGetIntegerv GL_ALPHA_TEST_FUNC 1 ALWAYS }
{ glGetIntegerv GL_ALPHA_TEST_REF 1 0 }
{ glIsEnabled GL_STENCIL_TEST 1 False }
{ glGetIntegerv GL_STENCIL_FUNC 1 ALWAYS }
{ glGetIntegerv GL_STENCIL_VALUE_MASK 1 1's }
{ glGetIntegerv GL_STENCIL_REF 1 0 }
{ glGetIntegerv GL_STENCIL_FAIL 1 KEEP }
{ glGetIntegerv GL_STENCIL_PASS_DEPTH_FAIL 1 KEEP }
{ glGetIntegerv GL_STENCIL_PASS_DEPTH_PASS 1 KEEP }
{ glGetIntegerv GL_STENCIL_BACK_FUNC 1 ALWAYS }
{ glGetIntegerv GL_STENCIL_BACK_VALUE_MASK 1 1's }
{ glGetIntegerv GL_STENCIL_BACK_REF 1 0 }
{ glGetIntegerv GL_STENCIL_BACK_FAIL 1 KEEP }
{ glGetIntegerv GL_STENCIL_BACK_PASS_DEPTH_FAIL 1 KEEP }
{ glGetIntegerv GL_STENCIL_BACK_PASS_DEPTH_PASS 1 KEEP }
{ glIsEnabled GL_DEPTH_TEST 1 False }
{ glGetIntegerv GL_DEPTH_FUNC 1 LESS }
{ glIsEnabled GL_BLEND 1 False }
{ glGetIntegerv GL_BLEND_SRC_RGB 1 ONE }
{ glGetIntegerv GL_BLEND_SRC 1 ONE }
{ glGetIntegerv GL_BLEND_SRC_ALPHA 1 ONE }
{ glGetIntegerv GL_BLEND_DST_RGB 1 ZERO }
{ glGetIntegerv GL_BLEND_DST 1 ZERO }
{ glGetIntegerv GL_BLEND_DST_ALPHA 1 ZERO }
{ glGetIntegerv GL_BLEND_EQUATION_RGB 1 FUNC_ADD }
{ glGetIntegerv GL_BLEND_EQUATION 1 FUNC_ADD }
{ glGetIntegerv GL_BLEND_EQUATION_ALPHA 1 FUNC_ADD }
{ glGetFloatv GL_BLEND_COLOR 4 0,0,0,0 }
{ glIsEnabled GL_DITHER 1 True }
{ glIsEnabled GL_INDEX_LOGIC_OP 1 False }
{ glIsEnabled GL_LOGIC_OP 1 False }
{ glIsEnabled GL_COLOR_LOGIC_OP 1 False }
{ glGetIntegerv GL_LOGIC_OP_MODE 1 COPY }
{ glGetIntegerv GL_DRAW_BUFFER_i 1 {see 4.2.1} }
{ glGetIntegerv GL_INDEX_WRITEMASK 1 1's }
{ glGetBooleanv GL_COLOR_WRITEMASK 1 True }
{ glGetBooleanv GL_DEPTH_WRITEMASK 1 True }
{ glGetIntegerv GL_STENCIL_WRITEMASK 1 1's }
{ glGetIntegerv GL_STENCIL_BACK_WRITEMASK 1 1's }
{ glGetFloatv GL_COLOR_CLEAR_VALUE 4 0,0,0,0 }
{ glGetFloatv GL_INDEX_CLEAR_VALUE 1 0 }
{ glGetIntegerv GL_DEPTH_CLEAR_VALUE 1 1 }
{ glGetIntegerv GL_STENCIL_CLEAR_VALUE 1 0 }
{ glGetFloatv GL_ACCUM_CLEAR_VALUE 1 0 }
{ glGetBooleanv GL_UNPACK_SWAP_BYTES 1 False }
{ glGetBooleanv GL_UNPACK_LSB_FIRST 1 False }
{ glGetIntegerv GL_UNPACK_IMAGE_HEIGHT 1 0 }
{ glGetIntegerv GL_UNPACK_SKIP_IMAGES 1 0 }
{ glGetIntegerv GL_UNPACK_ROW_LENGTH 1 0 }
{ glGetIntegerv GL_UNPACK_SKIP_ROWS 1 0 }
{ glGetIntegerv GL_UNPACK_SKIP_PIXELS 1 0 }
{ glGetIntegerv GL_UNPACK_ALIGNMENT 1 4 }
{ glGetBooleanv GL_PACK_SWAP_BYTES 1 False }
{ glGetBooleanv GL_PACK_LSB_FIRST 1 False }
{ glGetIntegerv GL_PACK_IMAGE_HEIGHT 1 0 }
{ glGetIntegerv GL_PACK_SKIP_IMAGES 1 0 }
{ glGetIntegerv GL_PACK_ROW_LENGTH 1 0 }
{ glGetIntegerv GL_PACK_SKIP_ROWS 1 0 }
{ glGetIntegerv GL_PACK_SKIP_PIXELS 1 0 }
{ glGetIntegerv GL_PACK_ALIGNMENT 1 4 }
{ glGetBooleanv GL_MAP_COLOR 1 False }
{ glGetBooleanv GL_MAP_STENCIL 1 False }
{ glGetIntegerv GL_INDEX_SHIFT 1 0 }
{ glGetIntegerv GL_INDEX_OFFSET 1 0 }
{ glGetFloatv GL_RED_SCALE 1 1 }
{ glGetFloatv GL_GREEN_SCALE 1 1 }
{ glGetFloatv GL_BLUE_SCALE 1 1 }
{ glGetFloatv GL_ALPHA_SCALE 1 1 }
{ glGetFloatv GL_DEPTH_SCALE 1 1 }
{ glGetFloatv GL_RED_BIAS 1 0 }
{ glGetFloatv GL_GREEN_BIAS 1 0 }
{ glGetFloatv GL_BLUE_BIAS 1 0 }
{ glGetFloatv GL_ALPHA_BIAS 1 0 }
{ glGetFloatv GL_DEPTH_BIAS 1 0 }
{ glIsEnabled GL_COLOR_TABLE 1 False }
{ glIsEnabled GL_POST_CONVOLUTION_COLOR_TABLE 1 False }
{ glIsEnabled GL_POST_COLOR_MATRIX_COLOR_TABLE 1 False }
{ glGetColorTable GL_COLOR_TABLE 1 empty }
{ glGetColorTable GL_POST_CONVOLUTION_COLOR_TABLE 1 empty }
{ glGetColorTable GL_POST_COLOR_MATRIX_COLOR_TABLE 1 empty }
{ glGetColorTableParameteriv GL_COLOR_TABLE_FORMAT 1 RGBA }
{ glGetColorTableParameteriv GL_COLOR_TABLE_WIDTH 1 0 }
{ glGetColorTableParameteriv GL_COLOR_TABLE_RED_SIZE 1 0 }
{ glGetColorTableParameteriv GL_COLOR_TABLE_GREEN_SIZE 1 0 }
{ glGetColorTableParameteriv GL_COLOR_TABLE_BLUE_SIZE 1 0 }
{ glGetColorTableParameteriv GL_COLOR_TABLE_ALPHA_SIZE 1 0 }
{ glGetColorTableParameteriv GL_COLOR_TABLE_LUMINANCE_SIZE 1 0 }
{ glGetColorTableParameteriv GL_COLOR_TABLE_INTENSITY_SIZE 1 0 }
{ glGetColorTableParameterfv GL_COLOR_TABLE_SCALE 4 1,1,1,1 }
{ glGetColorTableParameterfv GL_COLOR_TABLE_BIAS 4 0,0,0,0 }
{ glIsEnabled GL_CONVOLUTION_1D 1 False }
{ glIsEnabled GL_CONVOLUTION_2D 1 False }
{ glIsEnabled GL_SEPARABLE_2D 1 False }
{ glGetConvolutionFilter GL_CONVOLUTION_1D 1 empty }
{ glGetConvolutionFilter GL_CONVOLUTION_2D 1 empty }
{ glGetSeparableFilter GL_SEPARABLE_2D 1 empty }
{ glGetConvolutionParameterfv GL_CONVOLUTION_BORDER_COLOR 4 0,0,0,0 }
{ glGetConvolutionParameteriv GL_CONVOLUTION_BORDER_MODE 1 REDUCE }
{ glGetConvolutionParameterfv GL_CONVOLUTION_FILTER_SCALE 4 1,1,1,1 }
{ glGetConvolutionParameterfv GL_CONVOLUTION_FILTER_BIAS 4 0,0,0,0 }
{ glGetConvolutionParameteriv GL_CONVOLUTION_FORMAT 1 RGBA }
{ glGetConvolutionParameteriv GL_CONVOLUTION_WIDTH 1 0 }
{ glGetConvolutionParameteriv GL_CONVOLUTION_HEIGHT 1 0 }
{ glGetFloatv GL_POST_CONVOLUTION_RED_SCALE 1 1 }
{ glGetFloatv GL_POST_CONVOLUTION_GREEN_SCALE 1 1 }
{ glGetFloatv GL_POST_CONVOLUTION_BLUE_SCALE 1 1 }
{ glGetFloatv GL_POST_CONVOLUTION_ALPHA_SCALE 1 1 }
{ glGetFloatv GL_POST_CONVOLUTION_RED_BIAS 1 0 }
{ glGetFloatv GL_POST_CONVOLUTION_GREEN_BIAS 1 0 }
{ glGetFloatv GL_POST_CONVOLUTION_BLUE_BIAS 1 0 }
{ glGetFloatv GL_POST_CONVOLUTION_ALPHA_BIAS 1 0 }
{ glGetFloatv GL_POST_COLOR_MATRIX_RED_SCALE 1 1 }
{ glGetFloatv GL_POST_COLOR_MATRIX_GREEN_SCALE 1 1 }
{ glGetFloatv GL_POST_COLOR_MATRIX_BLUE_SCALE 1 1 }
{ glGetFloatv GL_POST_COLOR_MATRIX_ALPHA_SCALE 1 1 }
{ glGetFloatv GL_POST_COLOR_MATRIX_RED_BIAS 1 0 }
{ glGetFloatv GL_POST_COLOR_MATRIX_GREEN_BIAS 1 0 }
{ glGetFloatv GL_POST_COLOR_MATRIX_BLUE_BIAS 1 0 }
{ glGetFloatv GL_POST_COLOR_MATRIX_ALPHA_BIAS 1 0 }
{ glIsEnabled GL_HISTOGRAM 1 False }
{ glGetHistogram GL_HISTOGRAM 1 empty }
{ glGetHistogramParameteriv GL_HISTOGRAM_WIDTH 1 0 }
{ glGetHistogramParameteriv GL_HISTOGRAM_FORMAT 1 RGBA }
{ glGetHistogramParameteriv GL_HISTOGRAM_RED_SIZE 1 0 }
{ glGetHistogramParameteriv GL_HISTOGRAM_GREEN_SIZE 1 0 }
{ glGetHistogramParameteriv GL_HISTOGRAM_BLUE_SIZE 1 0 }
{ glGetHistogramParameteriv GL_HISTOGRAM_ALPHA_SIZE 1 0 }
{ glGetHistogramParameteriv GL_HISTOGRAM_LUMINANCE_SIZE 1 0 }
{ glGetHistogramParameteriv GL_HISTOGRAM SINK 1 False }
{ glIsEnabled GL_MINMAX 1 False }
{ glGetMinmax GL_MINMAX 8 M,M,M,M),(m,m,m,m }
{ glGetMinmaxParameteriv GL_MINMAX_FORMAT 1 RGBA }
{ glGetMinmaxParameteriv GL_MINMAX_SINK 1 False }
{ glGetFloatv GL_ZOOM_X 1 1.0 }
{ glGetFloatv GL_ZOOM_Y 1 1.0 }
{ glGetPixelMapfv GL_PIXEL_MAP_I_TO_I 1 0's }
{ glGetPixelMapfv GL_PIXEL_MAP_S_TO_S 1 0's }
{ glGetPixelMapfv GL_PIXEL_MAP_I_TO_R 1 0's }
{ glGetPixelMapfv GL_PIXEL_MAP_I_TO_G 1 0's }
{ glGetPixelMapfv GL_PIXEL_MAP_I_TO_B 1 0's }
{ glGetPixelMapfv GL_PIXEL_MAP_I_TO_A 1 0's }
{ glGetPixelMapfv GL_PIXEL_MAP_R_TO_R 1 0's }
{ glGetPixelMapfv GL_PIXEL_MAP_G_TO_G 1 0's }
{ glGetPixelMapfv GL_PIXEL_MAP_B_TO_B 1 0's }
{ glGetPixelMapfv GL_PIXEL_MAP_A_TO_A 1 0's }
{ glGetIntegerv GL_PIXEL_MAP_I_TO_I_SIZE 1 1 }
{ glGetIntegerv GL_PIXEL_MAP_S_TO_S_SIZE 1 1 }
{ glGetIntegerv GL_PIXEL_MAP_I_TO_R_SIZE 1 1 }
{ glGetIntegerv GL_PIXEL_MAP_I_TO_G_SIZE 1 1 }
{ glGetIntegerv GL_PIXEL_MAP_I_TO_B_SIZE 1 1 }
{ glGetIntegerv GL_PIXEL_MAP_I_TO_A_SIZE 1 1 }
{ glGetIntegerv GL_PIXEL_MAP_R_TO_R_SIZE 1 1 }
{ glGetIntegerv GL_PIXEL_MAP_G_TO_G_SIZE 1 1 }
{ glGetIntegerv GL_PIXEL_MAP_B_TO_B_SIZE 1 1 }
{ glGetIntegerv GL_PIXEL_MAP_A_TO_A_SIZE 1 1 }
{ glGetIntegerv GL_READ_BUFFER 1 {see 4.3.2} }
{ glGetMapiv GL_ORDER 1 1 }
{ glGetMapiv GL_ORDER 2 1,1 }
{ glGetMapfv GL_COEFF 1 {see 5.1} }
{ glGetMapfv GL_COEFF 1 {see 5.1} }
{ glGetMapfv GL_DOMAIN 1 {see 5.1} }
{ glGetMapfv GL_DOMAIN 1 {see 5.1} }
{ glIsEnabled GL_MAP1_NORMAL 1 False }
{ glIsEnabled GL_MAP2_NORMAL 1 False }
{ glGetFloatv GL_MAP1_GRID_DOMAIN 2 0,1 }
{ glGetFloatv GL_MAP2_GRID_DOMAIN 3 {0,1;0,1} }
{ glGetFloatv GL_MAP1_GRID_SEGMENTS 1 1 }
{ glGetFloatv GL_MAP2_GRID_SEGMENTS 2 1,1 }
{ glIsEnabled GL_AUTO_NORMAL 1 False }
{ glGetShaderSource - 1 empty }
{ glGetIntegerv GL_CURRENT_PROGRAM 1 0 }
{ glGetProgramiv GL_DELETE_STATUS 1 False }
{ glGetProgramiv GL_LINK_STATUS 1 False }
{ glGetProgramiv GL_VALIDATE_STATUS 1 False }
{ glGetProgramiv GL_ATTACHED_SHADERS 1 0 }
{ glGetAttachedObjects - 1 empty }
{ glGetProgramiv GL_INFO_LOG_LENGTH 1 0 }
{ glGetProgramiv GL_ACTIVE_UNIFORMS 1 0 }
{ glGetUniformLocation - 1 - }
{ glGetActiveUniform - 1 - }
{ glGetActiveUniform - 1 - }
{ glGetActiveUniform - 1 empty }
{ glGetProgramiv GL_ACTIVE_UNIFORM_MAX_LENGTH 1 0 }
{ glGetUniformfv - 1 0 }
{ glGetProgramiv GL_ACTIVE_ATTRIBUTES 1 0 }
{ glGetAttribLocation - 1 - }
{ glGetActiveAttrib - 1 - }
{ glGetActiveAttrib - 1 - }
{ glGetActiveAttrib - 1 empty }
{ glGetProgramiv GL_ACTIVE_ATTRIBUTES_MAX_LENGTH 1 0 }
{ glIsEnabled GL_VERTEX_PROGRAM_TWO_SIDE 1 False }
{ glGetVertexAttribfv GL_CURRENT_VERTEX_ATTRIB 4 0,0,0,1 }
{ glIsEnabled GL_VERTEX_PROGRAM_POINT_SIZE 1 False }
{ glGetIntegerv GL_PERSPECTIVE_CORRECTION_HINT 1 DONT_CARE }
{ glGetIntegerv GL_POINT_SMOOTH_HINT 1 DONT_CARE }
{ glGetIntegerv GL_LINE_SMOOTH_HINT 1 DONT_CARE }
{ glGetIntegerv GL_POLYGON_SMOOTH_HINT 1 DONT_CARE }
{ glGetIntegerv GL_FOG_HINT 1 DONT_CARE }
{ glGetIntegerv GL_GENERATE_MIPMAP_HINT 1 DONT_CARE }
{ glGetIntegerv GL_TEXTURE_COMPRESSION_HINT 1 DONT_CARE }
{ glGetIntegerv GL_FRAGMENT_SHADER_DERIVATIVE_HINT 1 DONT_CARE }
{ glGetIntegerv GL_MAX_LIGHTS 1 8 }
{ glGetIntegerv GL_MAX_CLIP_PLANES 1 6 }
{ glGetIntegerv GL_MAX_COLOR_MATRIX_STACK_DEPTH 1 2 }
{ glGetIntegerv GL_MAX_MODELVIEW_STACK_DEPTH 1 32 }
{ glGetIntegerv GL_MAX_PROJECTION_STACK_DEPTH 1 2 }
{ glGetIntegerv GL_MAX_TEXTURE_STACK_DEPTH 1 2 }
{ glGetIntegerv GL_SUBPIXEL_BITS 1 4 }
{ glGetIntegerv GL_MAX_3D_TEXTURE_SIZE 1 16 }
{ glGetIntegerv GL_MAX_TEXTURE_SIZE 1 64 }
{ glGetFloatv GL_MAX_TEXTURE_LOD_BIAS 1 2.0 }
{ glGetIntegerv GL_MAX_CUBE_MAP_TEXTURE_SIZE 1 16 }
{ glGetIntegerv GL_MAX_PIXEL_MAP_TABLE 1 32 }
{ glGetIntegerv GL_MAX_NAME_STACK_DEPTH 1 64 }
{ glGetIntegerv GL_MAX_LIST_NESTING 1 64 }
{ glGetIntegerv GL_MAX_EVAL_ORDER 1 8 }
{ glGetIntegerv GL_MAX_VIEWPORT_DIMS 1 {see 2.11.1} }
{ glGetIntegerv GL_MAX_ATTRIB_STACK_DEPTH 1 16 }
{ glGetIntegerv GL_MAX_CLIENT_ATTRIB_STACK_DEPTH 1 16 }
{ gl- - 1 32 }
{ gl- - 1 32 }
{ glGetIntegerv GL_AUX_BUFFERS 1 0 }
{ glGetBooleanv GL_RGBA_MODE 1 - }
{ glGetBooleanv GL_INDEX_MODE 1 - }
{ glGetBooleanv GL_DOUBLEBUFFER 1 - }
{ glGetBooleanv GL_STEREO 1 - }
{ glGetFloatv GL_ALIASED_POINT_SIZE_RANGE 2 1,1 }
{ glGetFloatv GL_SMOOTH_POINT_SIZE_RANGE 2 1,1 }
{ glGetFloatv GL_POINT_SIZE_RANGE 2 1,1 }
{ glGetFloatv GL_SMOOTH_POINT_SIZE_GRANULARITY 1 - }
{ glGetFloatv GL_POINT_SIZE_GRANULARITY 1 - }
{ glGetFloatv GL_ALIASED_LINE_WIDTH_RANGE 2 1,1 }
{ glGetFloatv GL_SMOOTH_LINE_WIDTH_RANGE 2 1,1 }
{ glGetFloatv GL_LINE_WIDTH_RANGE 2 1,1 }
{ glGetFloatv GL_SMOOTH_LINE_WIDTH_GRANULARITY 1 - }
{ glGetFloatv GL_LINE_WIDTH_GRANULARITY 1 - }
{ glGetConvolutionParameteriv GL_MAX_CONVOLUTION_WIDTH 1 3 }
{ glGetConvolutionParameteriv GL_MAX_CONVOLUTION_HEIGHT 1 3 }
{ glGetIntegerv GL_MAX_ELEMENTS_INDICES 1 - }
{ glGetIntegerv GL_MAX_ELEMENTS_VERTICES 1 - }
{ glGetIntegerv GL_SAMPLE_BUFFERS 1 0 }
{ glGetIntegerv GL_SAMPLES 1 0 }
{ glGetIntegerv GL_COMPRESSED_TEXTURE_FORMATS 1 - }
{ glGetIntegerv GL_NUM_COMPRESSED_TEXTURE_FORMATS 1 0 }
{ glGetQueryiv GL_QUERYCOUNTER_BITS 1 {see 6.1.12} }
{ glGetString GL_EXTENSIONS 1 - }
{ glGetString GL_RENDERER 1 - }
{ glGetString GL_SHADING_LANGUAGE_VERSION 1 - }
{ glGetString GL_VENDOR 1 - }
{ glGetString GL_VERSION 1 - }
{ glGetIntegerv GL_MAX_TEXTURE_UNITS 1 2 }
{ glGetIntegerv GL_MAX_VERTEX_ATTRIBS 1 16 }
{ glGetIntegerv GL_MAX_VERTEX_UNIFORM_COMPONENTS 1 512 }
{ glGetIntegerv GL_MAX_VARYING_FLOATS 1 32 }
{ glGetIntegerv GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS 1 2 }
{ glGetIntegerv GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS 1 0 }
{ glGetIntegerv GL_MAX_TEXTURE_IMAGE_UNITS 1 2 }
{ glGetIntegerv GL_MAX_TEXTURE_COORDS 1 2 }
{ glGetIntegerv GL_MAX_FRAGMENT_UNIFORM_COMPONENTS 1 64 }
{ glGetIntegerv GL_MAX_DRAW_BUFFERS 1 1+ }
{ glGetIntegerv GL_RED_BITS 1 - }
{ glGetIntegerv GL_GREEN_BITS 1 - }
{ glGetIntegerv GL_BLUE_BITS 1 - }
{ glGetIntegerv GL_ALPHA_BITS 1 - }
{ glGetIntegerv GL_INDEX_BITS 1 - }
{ glGetIntegerv GL_DEPTH_BITS 1 - }
{ glGetIntegerv GL_STENCIL_BITS 1 - }
{ glGetIntegerv GL_ACCUM_RED_BITS 1 - }
{ glGetIntegerv GL_ACCUM_GREEN_BITS 1 - }
{ glGetIntegerv GL_ACCUM_BLUE_BITS 1 - }
{ glGetIntegerv GL_ACCUM_ALPHA_BITS 1 - }
{ glGetIntegerv GL_LIST_BASE 1 0 }
{ glGetIntegerv GL_LIST_INDEX 1 0 }
{ glGetIntegerv GL_LIST_MODE 1 0 }
{ gl- - 1 empty }
{ glGetIntegerv GL_ATTRIB_STACK_DEPTH 1 0 }
{ gl- - 1 empty }
{ glGetIntegerv GL_CLIENT_ATTRIB_STACK_DEPTH 1 0 }
{ glGetIntegerv GL_NAME_STACK_DEPTH 1 0 }
{ glGetIntegerv GL_RENDER_MODE 1 RENDER }
{ glGetPointerv GL_SELECTION_BUFFER_POINTER 1 0 }
{ glGetIntegerv GL_SELECTION_BUFFER_SIZE 1 0 }
{ glGetPointerv GL_FEEDBACK_BUFFER_POINTER 1 0 }
{ glGetIntegerv GL_FEEDBACK_BUFFER_SIZE 1 0 }
{ glGetIntegerv GL_FEEDBACK_BUFFER_TYPE 1 2D }
{ glGetError - 1 0 }
{ gl- - 1 False }
{ gl- - 1 False }
{ glGetQueryiv GL_CURRENT_QUERY 1 0 }
{ gl- - 1 0 }
}
}
